name: CI
on: [pull_request]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn
        run: |
          corepack enable
          yarn

      - name: Lint
        run: yarn lint

      - name: Run Test and Report Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test --forceExit
          skip-step: install
